services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    ports:
      - "32400:32400"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - PLEX_CLAIM=claim-xxxxxxxxxxxxxxxxxxxx
      - VIRTUAL_HOST=plex.domain.com
      - VIRTUAL_PORT=32400
      - LETSENCRYPT_HOST=plex.domain.com
      - LETSENCRYPT_EMAIL=toto@yopmail.fr
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/config:/config
      - ./data/media:/data
    networks:
      - default
      - webproxy

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    restart: unless-stopped
    depends_on:
      - plex
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - VIRTUAL_HOST=plexpy.domain.com
      - VIRTUAL_PORT=8181
      - LETSENCRYPT_HOST=plexpy.domain.com
      - LETSENCRYPT_EMAIL=toto@yopmail.fr
    volumes:
      - ./data/tautulli:/config
      - ./data/media:/data
    ports:
      - "8181:8181"
    networks:
      - default
      - webproxy

networks:
  webproxy:
    external: true
